spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kata
    username: edita
    password: edita123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
